language: node_js
sudo: false
node_js:
  - "6"
  - "6.1"
  - "5.11"
cache:
  directories:
    - node_modules
before_install:
  - npm prune
install:
  - npm install
after_success:
  - 'npm run update-doc --silent'
